### ISSUE TITLE
ImportError: cannot import name 'apply_formatter_at_index'

### ISSUE THREAD

**Issue by nth193** [ethereum/eth-utils#112]
* Version: 1.0.3
* Python: 3.5
* OS: linux(Ubuntu 16.04)

### ImportError: cannot import name 'apply_formatter_at_index'

```
from web3 import Web3
  File "/lib/python3.5/site-packages/web3/__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402
  File "/lib/python3.5/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401
  File "/lib/python3.5/site-packages/eth_account/account.py", line 21, in <module>
    from eth_utils.curried import (
  File "/lib/python3.5/site-packages/eth_utils/curried/__init__.py", line 7, in <module>
    from eth_utils import (
ImportError: cannot import name 'apply_formatter_at_index'
```

### How can it be fixed?

**Comment by pipermerriam** [comment]
can you post the output of `pip freeze`

**Comment by EdwinGuo** [comment]
Any luck on this thread? Run into the same issue.

OS, mac High Sierra, version 10.13.4.
python3.6


> ➜  ~ pip freeze
argcomplete==1.9.3
asn1crypto==0.24.0
attrdict==2.0.0
backoff==1.6.0
base58==1.0.0
bitcoin==1.1.42
boto3==1.7.69
botocore==1.10.69
certifi==2018.4.16
cffi==1.11.5
cfn-flip==1.0.3
chardet==3.0.4
click==6.7
coincurve==8.0.2
cytoolz==0.9.0.1
docutils==0.14
durationpy==0.5
erc20token==0.1.8
eth-abi==1.1.1
eth-account==0.2.3
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b29
eth-testrpc==1.3.5
eth-utils==1.0.3
ethereum==2.3.1
ethereum-abi-utils==0.4.4
ethereum-keys==0.1.0a7
ethereum-tester==0.1.0b2
ethereum-utils==0.6.0
ethtoken==0.0.1a3
Flask==1.0.2
future==0.16.0
hexbytes==0.1.0
hjson==3.0.1
idna==2.7
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
json-rpc==1.11.0
kappa==0.6.0

>

**Comment by pipermerriam** [comment]
I highly suspect this is an environmental error of some kind.  I'd recommend wiping your python environment and re-installing.  If it is not fixed then, I'd be interested to see the actual contents of the source file in `eth_utils/__init__.py` as it is installed in your python environment.

**Comment by reedsa** [comment]
Closing this inactive thread, please open a new issue if you experience any further problems.
