### ISSUE TITLE
setuptools-markdown dependency unnecessary

### ISSUE THREAD

**Issue by jluttine** [ethereum/eth-utils#124]
PyPI supports Markdown formatted README files nowadays: https://packaging.python.org/guides/making-a-pypi-friendly-readme/

Thus, the dependency on `setuptools-markdown` can be removed. Also from the other `eth-*` packages.

**Comment by jluttine** [comment]
Hmm.. I may be wrong, actually. Perhaps the long_description field is required whenever packaging, so it's not PyPI related. Anyway, just for your information.

**Comment by carver** [comment]
Hm, I'm not *sure* we've tried this line from the linked docs:

```py
    long_description_content_type='text/markdown'
```

I'd be happy to get rid of the dependency, but also... it's working and not at the top of my list to test out this change. If someone feels like testing with a dummy pypi deployment to confirm that the content-type change would work, I'm happy to :+1: a PR making the change.

**Comment by carver** [comment]
This change is implemented in #207
