### ISSUE TITLE
Should is_hex() return False if the argument is not a str?

### ISSUE THREAD

**Issue by carver** [ethereum/eth-utils#137]
### What was wrong?

It might be inconvenient for people to have `is_hex()` raise a `TypeError` if the argument is a string. It always forces a double-check:

```py
if is_string(val) and is_hex(val):
    ...
```

### How can it be fixed?

We could simply `return False` if the value is not a `str`. If this is the route we go, it should be added to v2-alpha, but not v1. There are backwards incompatibility problems, like:

```py
try:
  if is_hex(val):
    return val
  else:
    # this code block currently gets to presume a string, but would crash during concatenation after the change
    raise ValidationError("string " + value + " must be hex")
except TypeError:
  # after the change this wouldn't run, which is fine I guess
  raise ValidationError(f"{value} must be a string")
```

@pipermerriam At first, I was very in favor of returning `False`, but after thinking a bit longer, I'm not so sure. People regularly confuse `bytes` <-> `str`, so it might just feel broken to them when they try as `is_hex(bytes_val)` and it always returns false. It's nice to be in their face that they are trying to do something that doesn't make sense.

Maybe there could be a new `is_hexstr()` that would have this new behavior of returning False on anything that's not a `str`. Then hopefully `is_hexstr(bytes_val)` would look more... wrong. This could be backported into v1 as well.

**Comment by pipermerriam** [comment]
> Maybe there could be a new `is_hexstr()` that would have this new behavior of returning False on anything that's not a `str`. Then hopefully `is_hexstr(bytes_val)` would look more... wrong. This could be backported into v1 as well.

:+1: to `is_hexstr()` and maybe adding a deprecation warning to `is_hex`

**Comment by Swixx** [comment]
@pipermerriam can I take this?
