### ISSUE TITLE
Decorator to convert to NamedTuple

### ISSUE THREAD

**Issue by Bhargavasomu** [ethereum/eth-utils#145]
### What was wrong?
Maybe it would be better if we had a `decorator` to convert key value pairs coming out in the form of `generators` or `dictionaries` to a `NamedTuple`. Something on the lines of `to_NamedTuple(tupleType)`.

### How can it be fixed?
It should be simple to add the decorator from the existing API similar to `to_dict` etc

**Comment by Bhargavasomu** [comment]
@pipermerriam the following points were what I was thinking.
* The `decorator` would have to take a `NamedTuple derived class` as an argument and will convert the input `generator object` or `dict` to the `NamedTuple class` which was passed as argument to the `Decorator`.
* The above stated passing as `argument` should also solve the type hinting issue.

For example,
```
class Person(NamedTuple):
    fname: str
    lname: str

@to_NamedTuple(Person)
def do_something():
    yield "fname", "Somu"
    yield "lname", "Bhargava"
```
Because we are passing the class `Person` as argument to the decorator, I think we should be able to design the `to_NamedTuple` function (or) decorator in such a way that the returned type is of the passed class type.

**Comment by pipermerriam** [comment]
Yes, that should be viable, though maybe we can start with the implementation living in the `trinity` codebase where I think you're looking to use this and elevate it to an `eth-utils` API if it proves useful.

**Comment by reedsa** [comment]
Closing as stale
