### ISSUE TITLE
Curried functions don't play nicely with type hinting

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/eth-utils#156]
### What was wrong?

Now that `eth-typing` is properly exposing types for functions and `mypy` is better at using those, this code throws errors.

```python
from_hex_to_bytes = hexstr_if_str(to_bytes)
# error: Too few arguments for "hexstr_if_str"
```

### How can it be fixed?

There may be a better way but the following seems to work.

Use [`typing.overload`](https://docs.python.org/3/library/typing.html#typing.overload) to manually declare the various allowed signatures and then define the curried version. 

```python
T = TypeVar("T")


@overload
def hexstr_if_str() -> Callable[[Callable[..., T], Union[bytes, int, str]], T]:
    pass


@overload
def hexstr_if_str(to_type: Callable[..., T]) -> Callable[[Union[bytes, int, str]], T]:
    pass


@overload
def hexstr_if_str(
    to_type: Callable[..., T], hexstr_or_primitive: Union[bytes, int, str]
) -> T:
    pass


def hexstr_if_str(
    to_type: Callable[..., T] = None, hexstr_or_primitive: Union[bytes, int, str] = None
) -> T:
    pass


hexstr_if_str = curry(_hexstr_if_str)
```

**Comment by davesque** [comment]
Yeah, at times I've thought we should ease back on the functional stuff.  This feels like one good example of why.  Other times, I think functional code can actually be less readable (and is probably inherently less performant in many cases).  I'm in favor of it when it improves readability and stability.
