### ISSUE TITLE
from_wei and to_wei argument order should be reversed.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/eth-utils#157]
### What is wrong.

I think the argument order of `to_wei` and `from_wei` is backwards.

This is based on trying to curry these functions and having to use a keyword argument for the units since it comes second.  Ideally we should be able to do `to_ether = eth_utils.curried.from_wei('ether')`

### How can it be fixed.

This should go though a full and long deprecation cycle.  We should be able to alter these functions so that they negotiate their arguments by checking types and raise deprecation warnings if the old way is provided.  Given the ubiquity of `eth-utils` and the levity of introducing breaking changes I think this should go through at least 6-12 months of issuing warnings before we move towards full deprecation.

**Comment by carver** [comment]
The hitch I see here is the natural order of describing it in English, "1 ether". Converting to "ether 1" from wei sounds really weird in my head. Usually I'm pretty loose on the argument ordering, and prefer the most natural currying order. But these two arguments seem to have a super natural ordering.

Other than some annoyance about having to type out currying via kwarg (which hopefully isn't happening a ton), do you see any other benefits from this switchover?

**Comment by pipermerriam** [comment]
I'm convinced they are better left as-is.  Good argument about natural ordering.
