### ISSUE TITLE
Cache whether `DEBUG2` is enabled on `ExtendedDebugLogger`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/eth-utils#159]
### What was wrong?

The previous implementation of `ExtendedDebugLogger` cached whether the `DEBUG2` level was enabled.

https://github.com/ethereum/py-evm/blob/5c080532168f38023bfebcd4ec60bb68c70fd29d/eth/tools/logging.py#L9-L13

### How can it be fixed?

Use the same pattern for the `eth-utils` version of the logger.

**Comment by reedsa** [comment]
This has been implemented: https://github.com/ethereum/eth-utils/blob/78dc6459f5ea847d8e1a6b50bb656abadcdea865/eth_utils/logging.py#L33C23-L33C49
