### ISSUE TITLE
`to_wei` type hint too strict

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/eth-utils#168]
### What was wrong?

The type hint for [to_wei](https://github.com/ethereum/eth-utils/blob/faff9e0a7373b623b3203f6046cbf75d7400b07a/eth_utils/currency.py#L64-L102) only allows `int`s, but the implementation also accepts `float`s, `str`s, and `Decimal`s.

### How can it be fixed?

Update the type hint to, if I haven't missed anything, `Union[int, float, str, Decimal]`.

**Comment by Patil2099** [comment]
Can I work on this issue? @jannikluhn @pipermerriam

**Comment by cburgdorf** [comment]
@Patil2099 feel free to tackle this!
