### ISSUE TITLE
Wrong type hint for remove_0x_prefix

### ISSUE THREAD

**Issue by feuGeneA** [ethereum/eth-utils#176]
* Version: 1.8.1
* Python: 3/8/2
* OS: linux

### What was wrong?

I have some existing code that uses `remove_0x_prefix()`, and I've been running mypy on my code in my CI system for quite some time, and upon the upgrade to eth_utils 1.8.1 my mypy runs started failing.  Here's a stripped down repro, using the example from the doc for this function:

```bash
$ cat tmp.py 
from eth_utils import remove_0x_prefix
remove_0x_prefix('0x12345')
```

```bash
$ mypy tmp.py
tmp.py:2: error: Argument 1 to "remove_0x_prefix" has incompatible type "str"; expected "HexStr"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by pipermerriam** [comment]
We are now using the type `eth_typing.HexStr` to enforce differentiation between normal `str` types and hex encoded data as a string.  You can do this: 

```python
from eth_typing import HexStr
remove_0x_prefix(HexStr('0x1234'))
```

**Comment by feuGeneA** [comment]
Then isn't this a bug in the docs?

**Comment by feuGeneA** [comment]
The doc says this function's argument "`must be string literal.`"  If you follow the doc, you end up with a mypy error.  Seems to me that either the type annotation should be amended to permit a string literal, or the doc should be updated to say it requires a `HexStr`.

**Comment by pipermerriam** [comment]
cc @njgheorghita yes, definitely a docs bug that should be updated.
