### ISSUE TITLE
Missing `setuptools` requirement.

### ISSUE THREAD

**Issue by Adi-Yakovian** [ethereum/eth-utils#224]
## What was wrong?

Missing setuptools requirement, even though it is needed [here](https://github.com/ethereum/eth-utils/blob/9d0ba061c55161849ae31a99326329534e0ed1b2/eth_utils/__init__.py#L4).

## How can it be fixed?

Add the requirement in `setup.py`.

**Comment by reedsa** [comment]
Thanks for submitting this issue. Is there an error you are encountering?
Adding the requirement does not appear to be necessary, is there anything in particular you saw?

Closing this but please file another issue if you have further questions!
