### ISSUE TITLE
DeprecationWarning : toolz.compatibility

### ISSUE THREAD

**Issue by maxclax** [ethereum/eth-utils#234]
```
eth_utils/toolz.py:2: DeprecationWarning: The toolz.compatibility module is no longer ne│
eded in Python 3 and has been deprecated. Please import these utilities directly from the standard library. This module will be│
 removed in a future release.
```

**Comment by reedsa** [comment]
Hello, thanks for reaching out and apologies for the delay in our response. Could you please provide more information about the warning you found and what version of eth-utils you are using?

`toolz.compatibility` was [removed in eth-utils v2](https://github.com/ethereum/eth-utils/commit/fbec4fc3e32765f6c110f004982a595908df523d) and should no longer throw this warning.
