### ISSUE TITLE
Network name utility

### ISSUE THREAD

**Issue by reedsa** [ethereum/eth-utils#253]
### What feature should we add?

It would be convenient to retrieve the network name by using `w3.network`, which could just call the utility with  `w3.eth.chain_id`.

A `name_from_chain_id` function is needed that will return the full name of the network. (example: "Ethereum Mainnet")
A `short_name_from_chain_id` function would return the short name. (example: "eth")

List of networks in json: https://chainid.network/chains_mini.json

A script was written to parse the list json and create a list of enums: https://gist.github.com/reedsa/addafe9eb852db3267c0e90f1ce9867e
An adaptation of the script could make it easy to update the list chain ids and names in our code.

**Comment by DavidRomanovizc** [comment]
Hello @reedsa! I'd like to try to contribute and solve this issue. Could you please provide me with further instructions and assign this task to me?

**Comment by reedsa** [comment]
@DavidRomanovizc sounds great! The network utility functions can be added to a new python file under `eth_utils`.

Considering Python's dictionary already provides an efficient lookup mechanism, the utility file could set one variable that contains the names and another variable contains the short names for each network.

```python
network_names_by_id = {
    1: "Ethereum Mainnet",
    ...
}
```

That way all the utility function would need to do is return the result of `network_names.get(chain_id)`.

```
def name_from_chain_id(chain_id: int):
    return network_names_by_id.get(chain_id)
```

The same pattern applies for the short names. Parameterized tests should be added as well to make sure the new functions are returning what is expected.

Again, appreciate your help on this. If you have any questions feel free to reach out!
