### ISSUE TITLE
`v5` Breaking Changes

### ISSUE THREAD

**Issue by reedsa** [ethereum/eth-utils#281]
### What feature should we add?

Changes for `v5` to include ABI utils.

Also planing to close PRs linked to this issue.
```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/eth-utils/pull/271
- [ ] https://github.com/ethereum/eth-utils/pull/230
```

**Comment by kclowes** [comment]
Maybe move exceptions to inherit from EthUtilsException?
