### ISSUE TITLE
python 3.6 (3.7?) in setup.py and elsewhere

### ISSUE THREAD

**Issue by themusicgod1** [ethereum/eth-utils#32]
* Version: 1.0.0
* Python: 3.6 / 3.7
* OS: ubuntu 18.04 bionic / *

### What was wrong?

Right now in setup.py and elsewhere there's some hardcoded mentioning of python 3.4 3.5 ...but now with 3.6 (and 3.7?) out it's probably a good idea to explicitly bump that version in there too.

ie
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
    ],

to
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
    ],

tox.ini:
basepython =
    py27: python2.7
    py34: python3.4
    py35: python3.5

to
basepython =
    py27: python2.7
    py34: python3.4
    py35: python3.5
    py36: python3.6
etc

### How can it be fixed?

see above

**Comment by pipermerriam** [comment]
fixed via #35
