### ISSUE TITLE
Extract many utilities from web3 into eth-utils

### ISSUE THREAD

**Issue by carver** [ethereum/eth-utils#47]
## What was wrong?

Web3.py has added a number of utilities that other Ethereum libraries might find useful. For example, we are in the process of extracting the local signing code from web3 to `eth-account` (working name), and it depends on datastructures, conversions, and decorators that don't really have much to do with Web3, but are currently housed there.

### Extract to eth-utils

- decorators
   - combomethod,
- encoding
   - hexstr_if_str,
   - text_if_str,
   - to_bytes,
   - to_int,
   - to_hex,
   - to_text,
  - ?
- ?

### Add to a new eth-rlp

- HashableRLP
- Transaction(rlp.Serializable)
- ?

### Add to a new `hexbytes`

HexBytes

### Compose from available libraries
FrozenAttributeDict = compose(AttrDict, frozendict)

**Comment by carver** [comment]
Some RLP utilities would be nice. The `ExtendedRLP` class would be nice to share (maybe renamed to `HashableRLP` or something). But adding a dependency to pyrlp feels a bit wrong. Thoughts?

Maybe it belongs in another eth-rlp that depends on rlp and eth-utils.

**Comment by pipermerriam** [comment]
I'm thinking that we could make some *micro* packages for some of the data structures to avoid bloating eth-utils.  I'd be good with the following

- bring in all the encoding utils listed.
- `AttributeDict` to it's own package **if** we have a secondary use case for it.
- `HexBytes` to it's own package **if** we have a secondary use case for it.
- `ExtendedRLP -> HashableRLP` to it's own package (`eth-rlp` is fine with me)
- new `eth-validation` package to bring together many of the validation utils that we've written across `py-evm`, `web3.py`, and what is about to get written in `trinity`.

👍 
I don't know what `ExtendedRLP` class could

**Comment by pipermerriam** [comment]
oh, and what's the secondary use case for `combomethod`?

**Comment by carver** [comment]
> I don't know what ExtendedRLP class could

(Guessing at the second half of the sentence) Yeah, actually maybe that's only useful in `eth-account`. I'll keep futzing with it.

> oh, and what's the secondary use case for combomethod?

Relatively minor, maybe there's some better solution: `Account` can be used statically with the default eth-keys backend, or you can initialize it and set a different eth-keys backend on your instance.

**Comment by carver** [comment]
> AttributeDict to it's own package if we have a secondary use case for it.
HexBytes to it's own package if we have a secondary use case for it.

Since `eth-account` will be a proper end-user package (you could theoretically use it without web3), I'd like to keep returning values in friendly ways. That means joint key and attribute access (`AttributeDict`), and pretty display of `bytes` at the console (`HexBytes`).

I don't know if I will have the time to make separate packages for each of those, so maybe I'll just copy the data structures into eth-account for now if you are hesitant to add them to eth-utils.

---

Another one came up: the formatting appliers, like `apply_formatters_to_dict`.

That's used for converting values in a user-supplied transaction dict to a consistent type.

**Comment by pipermerriam** [comment]
Are you good with the following package names.  I'll stub them out so that they're ready for us.

- Thoughts on using: https://github.com/bcj/AttrDict ?  Brief scan of the docs suggest we should be able to just use it as a drop-in replacement.  Would be nice to extend the tests to our python versions.
- `property-dict` if we want to roll our own.
- `hexbytes`
- `eth-validation`

**Comment by carver** [comment]
> Thoughts on using: https://github.com/bcj/AttrDict ?

I am good with it. The only difference is that ours is immutable, and they seem unlikely to implement that any time soon: https://github.com/bcj/AttrDict/issues/28 . It's worth the tradeoff to me. Or maybe if it's okay to locally deal with it by choosing an immutable dict library and defining `FrozenAttrDict = compose(AttrDict, frozendict)`.

> property-dict if we want to roll our own.

If we need to roll our own, then I like attribute, since that seems the common name (getattr, setattr, etc). To distinguish from the existing attrdict, maybe `frozen-attr-dict`?

Other names look good :+1: 

I am working on an `eth-account` and `eth-rlp` locally, already.
