### ISSUE TITLE
Validate text and hexstr parameters are str type

### ISSUE THREAD

**Issue by carver** [ethereum/eth-utils#60]
* Version: 1

### What was wrong?

See [this comment](https://github.com/ethereum/eth-utils/pull/58#discussion_r167601284) about `bytes` being passed to `to_text` as `text=`. In that case `to_text()` returned a `bytes` value, which seems wrong.

### How can it be fixed?

Raise an exception if the `text` or `hexstr` parameters are not `str`, in any of the conversion methods.

**Comment by njgheorghita** [comment]
@carver would it be better to do this as a decorator? or inside the function

**Comment by carver** [comment]
I expect decorator would be a slight performance hit, but maybe cleaner. I don't have strong feelings on it, maybe a slight lean toward decorator.

A `@validate_conversion_arguments` decorator could do the type checks as well as make sure only one value is specified.
