### ISSUE TITLE
make `keccak` work for bytearrays

### ISSUE THREAD

**Issue by palango** [ethereum/eth-utils#74]
* Version: 1.0.0b2
* Python: 3.6
* OS: osx

### What was wrong?

When trying to hash a bytearray with the `keccak` function (`keccak(bytearray(b'abc'))`) it throws the following error:
```TypeError: expected an int in first arg, or keyword of hexstr or text```

There are to problems:
- The error message seems wrong, as the first argument can be a boolean or `bytes`
- More important: hashing should work for bytearrays as well. Or is there a reason this isn't implemented?

### How can it be fixed?

Make `keccak` work for bytearrays

**Comment by pipermerriam** [comment]
Adding support for this seems like it should be quite trivial.  +1 to adding it.  Would you be willing to make the pull request?

**Comment by pipermerriam** [comment]
@carver thoughts on whether this belongs in `eth-hash`?

**Comment by palango** [comment]
Yes, I can create a PR. Just wanted to know if it makes sense for you. This would also require small changes to `eth_hash`.

**Comment by pipermerriam** [comment]
> This would also require small changes to `eth_hash`.

Can you expand on that, seems like we *can* make the necessary normalization right here within `eth-utils` without any changes to `eth-hash`

I am supportive of adding support for `bytearrays` to the `eth-hash` library though so feel free to make the necessary PR to `eth-hash` and whatever changes needed in `eth-utils` to allow `bytearray` types to the `keccak` function here.

**Comment by palango** [comment]
We could either convert all bytearrays to bytes in `eth-utils` or fix the type checks in `eth-hash` like here: https://github.com/ethereum/eth-hash/blob/master/eth_hash/main.py#L8

**Comment by carver** [comment]
> @carver thoughts on whether this belongs in eth-hash?

Two initial thoughts:

1. It's nice to keep `eth-hash` very simple, so in general converting to bytes does not belong in eth-hash, IMO. For example, converting from a hex string to bytes should stay in eth-utils.
2. `bytes` and `bytearray`  are used nearly interchangeably in various places in the Python standard library. We've typically only supported `bytes` in web3.py for simplicity, but it's a little less consistent with Python standards.

Given point 2, I'm happy to see `eth-hash` support `bytearray`. Similarly, that implies we should also make the conversion utils support `bytearray` in the `primitive` field, like: `to_int`, `to_bytes`, `to_hex`, `to_text`.

**Comment by palango** [comment]
This will be fixed as soon as a new eth-hash version is released and required in eth-utils.

**Comment by pipermerriam** [comment]
`eth-hash==0.1.0` has just been released.  You can bump the dependency to `eth-hash>=0.1.0,<1.0.0`
