### ISSUE TITLE
Don't accept `str` as a primitive in `to_hex()`

### ISSUE THREAD

**Issue by carver** [ethereum/eth-utils#85]
* Version: 1.0.2
* Python: 3.5
* OS: osx/linux/win

### What was wrong?

`to_hex()` shouldn't presume the kind of `str` value in primitive. It's the kind of ambiguity we aim to avoid, using `hexstr` and `text` keyword args:
https://github.com/ethereum/eth-utils/blob/master/eth_utils/conversions.py#L41-L42

### How can it be fixed?

`to_hex()` should reject `str` values, by raising a TypeError and listing the accepted types: `(bytes, bytearray, int, bool)`

Double-check if this breaks anything in py-evm or web3.py

**Comment by palash25** [comment]
Can I take a crack at this @carver ?

**Comment by carver** [comment]
Sure! :+1:

**Comment by pipermerriam** [comment]
@stefanmendoza go for it

**Comment by palash25** [comment]
I didn't know this issue was still open I thought my PR must have closed this. Well in that case go for it @stefanmendoza

**Comment by stefanmendoza** [comment]
@palash25 ah, nevermind. Missed the PR in the history on this. I think this is good to close then. 👍 

cc @pipermerriam / @carver
