### ISSUE TITLE
To normalized address throws ValueError

### ISSUE THREAD

**Issue by PabloLefort** [ethereum/eth-utils#98]
* Version: 1.0.3
* Python: 3.6
* OS: osx

Running the same example off the Readme:
`to_normalized_address('0x000000000000000000000000c305c901078781c232a2a521c2af7980f8385ee9')`
throws:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File ".../lib/python3.6/site-packages/eth_utils/address.py", line 68, in to_normalized_address
    "Unknown format {}, attempted to normalize to {}".format(address, hex_address)
ValueError: Unknown format 0x000000000000000000000000c305c901078781c232a2a521c2af7980f8385ee9, attempted to normalize to 0x000000000000000000000000c305c901078781c232a2a521c2af7980f8385ee9
```

**Comment by carver** [comment]
IIRC, we dropped support for 32-byte addresses on the transition to v1, so this is a documentation bug.

**Comment by PabloLefort** [comment]
All right. A workaround could be:
```python
address = '0x000000000000000000000000c305c901078781c232a2a521c2af7980f8385ee9'
normalized_address = '0x{}'.format(address[2:].lstrip('0'))
```
Seems good for you @carver ?

Thanks in advance! :rocket:

**Comment by pipermerriam** [comment]
@PabloLefort I think you're code will fail if the address starts with any byte value or values which start with `0` when hex encoded.  Try the following.

```
def normalize_32_byte_hex_address(value):
    as_bytes = eth_utils.to_bytes(hexstr=value)
    return eth_utils.to_normalized_address(as_bytes[-20:])
```

Haven't tested the code above but it should get you moving in the right direction.
